name: Mac

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy: 
      matrix: 
        options: [--with-sb-thread, --without-sb-thread]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: instal host sbcl
      run: brew install sbcl
    - name: build
      env:  
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
      run: ./make.sh ${{ matrix.options }} --xc-host='sbcl --dynamic-space-size 500MB --lose-on-corruption --disable-ldb --disable-debugger'
    - name: make binary
      run: |
        name=sbcl-`cat version.lisp-expr | ./run-sbcl.sh --noinform --noprint --eval '(write-line (read))'`-darwin-x86-64
        mkdir sbcl-mac-binary${{ matrix.options }};
        cd ..
        mv sbcl $name
        ./$name/binary-distribution.sh $name
        bzip2 $name-binary.tar
        mv $name sbcl
        mv $name-binary.tar.bz2 sbcl/sbcl-mac-binary${{ matrix.options }}
    - name: save binary
      uses: actions/upload-artifact@v1
      with:
        name: sbcl-mac-binary${{ matrix.options }}
        path: sbcl-mac-binary${{ matrix.options }}
    - name: test
      run: cd tests; ./run-tests.sh
    - name: ansi-test
      run: cd tests; ./ansi-tests.sh
